image: node:18

stages:
  - build
  - deploy

cache:
  paths:
    - node_modules/

build:
  stage: build
  script:
    - npm install
    - npm run build
  artifacts:
    paths:
      - dist/
  only:
    - main

deploy_production:
  stage: deploy
  script:
    - echo "Deploy to production server"
  environment:
    name: production
  only:
    - main